// Auto-generated by Personal Report deploy script
'use client'
import { useState } from 'react'
const content = {
  zh: {
    nav: { about: '关于我', experience: '实习经历', projects: '项目经历', skills: '技能证书', contact: '联系方式' },
    hero: { name: '张三', title: '金融 + 数据分析', description: '天津大学金融硕士，擅长数据分析和行业研究，具备Python/SQL技术能力。', email: '' },
    about: { title: '关于我', intro: '天津大学金融硕士，擅长数据分析和行业研究，具备Python/SQL技术能力。', education: { school: '天津大学', degree: '金融硕士', period: '2024.09 - 2027.01', gpa: '92.21（专业前10%）', honors: '' } },
    experience: { title: '实习经历', items: [    {
      company: '某科技公司', companyEn: 'Tech Company',
      role: '资金分析实习生', roleEn: '资金分析实习生',
      period: '2025.12 - 至今', periodEn: '2025.12 - 至今',
      highlights: ['搭建资金看板，实现数据可视化', '自动化处理效率提升60%'],
      highlightsEn: ['Built fund dashboard with data visualization', 'Improved automation efficiency by 60%'],
    }] },
    projects: { title: '项目经历', items: [    {
      title: '基于LLM的行业相似度研究', titleEn: 'LLM-based Industry Similarity Research',
      subtitle: '', subtitleEn: '',
      tech: ['Python', 'BERT', 'Pandas'],
      objective: '使用BERT计算上市公司年报文本相似度，优化动量策略。', objectiveEn: '使用BERT计算上市公司年报文本相似度，优化动量策略。',
      methodology: '', methodologyEn: '',
      findings: '', findingsEn: '',
      status: '', statusEn: '',
    }] },
    skills: { title: '技能 & 证书', categories: [      { name: '', items: [] }] },
    contact: { title: '联系方式', email: '', phone: '', github: '', linkedin: '' },
  },
  en: {
    nav: { about: 'About', experience: 'Experience', projects: 'Projects', skills: 'Skills', contact: 'Contact' },
    hero: { name: 'San Zhang', title: 'Finance + Data Analytics', description: '天津大学金融硕士，擅长数据分析和行业研究，具备Python/SQL技术能力。', email: '' },
    about: { title: 'About Me', intro: '天津大学金融硕士，擅长数据分析和行业研究，具备Python/SQL技术能力。', education: { school: 'Tianjin University', degree: '金融硕士', period: '2024.09 - 2027.01', gpa: '92.21（专业前10%）', honors: '' } },
    experience: { title: 'Experience', items: [    {
      company: 'Tech Company', companyEn: 'Tech Company',
      role: '资金分析实习生', roleEn: '资金分析实习生',
      period: '2025.12 - 至今', periodEn: '2025.12 - 至今',
      highlights: ['Built fund dashboard with data visualization', 'Improved automation efficiency by 60%'],
      highlightsEn: ['Built fund dashboard with data visualization', 'Improved automation efficiency by 60%'],
    }] },
    projects: { title: 'Projects', items: [    {
      title: 'LLM-based Industry Similarity Research', titleEn: 'LLM-based Industry Similarity Research',
      subtitle: '', subtitleEn: '',
      tech: ['Python', 'BERT', 'Pandas'],
      objective: '使用BERT计算上市公司年报文本相似度，优化动量策略。', objectiveEn: '使用BERT计算上市公司年报文本相似度，优化动量策略。',
      methodology: '', methodologyEn: '',
      findings: '', findingsEn: '',
      status: '', statusEn: '',
    }] },
    skills: { title: 'Skills & Certifications', categories: [      { name: '', items: [] }] },
    contact: { title: 'Contact', email: '', phone: '', github: '', linkedin: '' },
  },
}
type Lang = 'zh' | 'en'
type Content = typeof content.zh
export default function HomePage() {
  const [lang, setLang] = useState<Lang>('zh')
  const t: Content = content[lang]
  return (
    <div className="min-h-screen bg-white">
      <nav className="fixed top-0 w-full bg-white/80 backdrop-blur-sm z-50 border-b border-gray-100">
        <div className="max-w-5xl mx-auto px-6 py-4 flex justify-between items-center">
          <span className="font-bold text-lg text-primary-700">{t.hero.name}</span>
          <div className="flex items-center gap-6">
            <a href="#about" className="text-sm text-gray-600 hover:text-primary-600">{t.nav.about}</a>
            <a href="#experience" className="text-sm text-gray-600 hover:text-primary-600">{t.nav.experience}</a>
            <a href="#projects" className="text-sm text-gray-600 hover:text-primary-600">{t.nav.projects}</a>
            <a href="#skills" className="text-sm text-gray-600 hover:text-primary-600">{t.nav.skills}</a>
            <a href="#contact" className="text-sm text-gray-600 hover:text-primary-600">{t.nav.contact}</a>
            <button onClick={() => setLang(lang === 'zh' ? 'en' : 'zh')} className="text-sm px-3 py-1 rounded-full bg-gray-100 hover:bg-gray-200">{lang === 'zh' ? 'EN' : '中文'}</button>
          </div>
        </div>
      </nav>
      <section className="pt-32 pb-20 px-6"><div className="max-w-5xl mx-auto">
        <h1 className="text-5xl font-bold text-gray-900 mb-4">{t.hero.name}</h1>
        <p className="text-xl text-primary-600 mb-6">{t.hero.title}</p>
        <p className="text-gray-600 max-w-2xl">{t.hero.description}</p>
      </div></section>
      <section id="about" className="py-20 px-6 bg-gray-50"><div className="max-w-5xl mx-auto">
        <h2 className="text-3xl font-bold text-gray-900 mb-8">{t.about.title}</h2>
        <p className="text-gray-600 mb-8">{t.about.intro}</p>
        <div className="bg-white rounded-xl p-6 shadow-sm">
          <h3 className="font-semibold text-lg mb-4">🎓 {t.about.education.school}</h3>
          <p className="text-gray-600">{t.about.education.degree} · {t.about.education.period}</p>
          {t.about.education.gpa && <p className="text-gray-500 mt-2">GPA: {t.about.education.gpa}</p>}
          {t.about.education.honors && <p className="text-gray-500">{t.about.education.honors}</p>}
        </div>
      </div></section>
      <section id="experience" className="py-20 px-6"><div className="max-w-5xl mx-auto">
        <h2 className="text-3xl font-bold text-gray-900 mb-8">{t.experience.title}</h2>
        <div className="space-y-6">{t.experience.items.map((exp: any, i: number) => (
          <div key={i} className="bg-white border border-gray-200 rounded-xl p-6">
            <div className="flex justify-between items-start mb-4">
              <div><h3 className="font-semibold text-lg">{exp.company}</h3><p className="text-primary-600">{exp.role}</p></div>
              <span className="text-sm text-gray-500">{exp.period}</span>
            </div>
            <ul className="space-y-2">{exp.highlights.map((h: string, j: number) => (
              <li key={j} className="text-gray-600 flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>{h}</li>
            ))}</ul>
          </div>))}</div>
      </div></section>
      <section id="projects" className="py-20 px-6 bg-gray-50"><div className="max-w-5xl mx-auto">
        <h2 className="text-3xl font-bold text-gray-900 mb-8">{t.projects.title}</h2>
        <div className="grid md:grid-cols-2 gap-6">{t.projects.items.map((proj: any, i: number) => (
          <div key={i} className="bg-white rounded-xl p-6 shadow-sm">
            <h3 className="font-semibold text-lg mb-2">{proj.title}</h3>
            {proj.tech?.length > 0 && <div className="flex flex-wrap gap-2 mb-3">{proj.tech.map((tech: string, j: number) => (
              <span key={j} className="text-xs px-2 py-1 bg-primary-50 text-primary-700 rounded-full">{tech}</span>
            ))}</div>}
            <p className="text-gray-600 text-sm">{proj.objective}</p>
          </div>))}</div>
      </div></section>
      <section id="skills" className="py-20 px-6"><div className="max-w-5xl mx-auto">
        <h2 className="text-3xl font-bold text-gray-900 mb-8">{t.skills.title}</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{t.skills.categories.filter((c: any) => c.items.length > 0).map((cat: any, i: number) => (
          <div key={i} className="bg-white border border-gray-200 rounded-xl p-6">
            <h3 className="font-semibold mb-4">{cat.name}</h3>
            <div className="flex flex-wrap gap-2">{cat.items.map((item: string, j: number) => (
              <span key={j} className="text-sm px-3 py-1 bg-gray-100 rounded-full">{item}</span>
            ))}</div>
          </div>))}</div>
      </div></section>
      <section id="contact" className="py-20 px-6 bg-gray-900 text-white"><div className="max-w-5xl mx-auto text-center">
        <h2 className="text-3xl font-bold mb-8">{t.contact.title}</h2>
        <div className="flex flex-wrap justify-center gap-6">
          {t.contact.email && <a href={"mailto:" + t.contact.email} className="text-gray-300 hover:text-white">📧 {t.contact.email}</a>}
          {t.contact.github && <a href={t.contact.github} target="_blank" className="text-gray-300 hover:text-white">💻 GitHub</a>}
          {t.contact.linkedin && <a href={t.contact.linkedin} target="_blank" className="text-gray-300 hover:text-white">🔗 LinkedIn</a>}
          {t.contact.phone && <span className="text-gray-300">📱 {t.contact.phone}</span>}
        </div>
      </div></section>
      <footer className="py-6 text-center text-gray-400 text-sm">Built with Personal Report · Next.js</footer>
    </div>
  )
}