/**
 * generatePage.js
 * 读取 userData.json（由 server.exe 生成），输出 app/page.tsx
 *
 * 用法：
 *   node scripts/generatePage.js <userData.json路径> <page.tsx输出路径>
 */

const fs = require('fs');
const path = require('path');

const dataPath = process.argv[2];
const outputPath = process.argv[3];

if (!dataPath || !outputPath) {
  console.error('用法：node generatePage.js <userData.json> <app/page.tsx>');
  process.exit(1);
}

if (!fs.existsSync(dataPath)) {
  console.error('找不到资料文件：' + dataPath);
  process.exit(1);
}

let userData;
try {
  userData = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
} catch (e) {
  console.error('读取资料文件失败：' + e.message);
  process.exit(1);
}

// 安全取值，避免 undefined
function s(v, fallback) {
  if (v === null || v === undefined || v === '') return fallback || '';
  return String(v).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');
}

// 将字符串数组安全序列化为 JS 字面量
function arr(a) {
  if (!Array.isArray(a)) return '[]';
  return '[' + a.map(x => JSON.stringify(x)).join(', ') + ']';
}

// 将经历/项目数组生成代码片段
function buildExperienceItems(items) {
  if (!Array.isArray(items) || items.length === 0) return '[]';
  return '[\n' + items.map(exp => {
    const highlights = Array.isArray(exp.highlights) ? exp.highlights : [];
    const highlightsEn = Array.isArray(exp.highlightsEn) ? exp.highlightsEn : highlights;
    return `    {
      company: ${JSON.stringify(exp.company || '')}, companyEn: ${JSON.stringify(exp.companyEn || exp.company || '')},
      role: ${JSON.stringify(exp.role || '')}, roleEn: ${JSON.stringify(exp.roleEn || exp.role || '')},
      period: ${JSON.stringify(exp.period || '')}, periodEn: ${JSON.stringify(exp.periodEn || exp.period || '')},
      highlights: ${JSON.stringify(highlights)},
      highlightsEn: ${JSON.stringify(highlightsEn)},
    }`;
  }).join(',\n') + '\n  ]';
}

function buildProjectItems(items) {
  if (!Array.isArray(items) || items.length === 0) return '[]';
  return '[\n' + items.map(proj => {
    const tech = Array.isArray(proj.tech) ? proj.tech : [];
    return `    {
      title: ${JSON.stringify(proj.title || '')}, titleEn: ${JSON.stringify(proj.titleEn || proj.title || '')},
      subtitle: ${JSON.stringify(proj.subtitle || '')}, subtitleEn: ${JSON.stringify(proj.subtitleEn || proj.subtitle || '')},
      tech: ${JSON.stringify(tech)},
      objective: ${JSON.stringify(proj.objective || proj.description || '')}, objectiveEn: ${JSON.stringify(proj.objectiveEn || proj.objective || proj.description || '')},
      methodology: ${JSON.stringify(proj.methodology || '')}, methodologyEn: ${JSON.stringify(proj.methodologyEn || '')},
      findings: ${JSON.stringify(proj.findings || '')}, findingsEn: ${JSON.stringify(proj.findingsEn || '')},
      status: ${JSON.stringify(proj.status || '')}, statusEn: ${JSON.stringify(proj.statusEn || '')},
    }`;
  }).join(',\n') + '\n  ]';
}

function buildSkillCategories(categories) {
  if (!Array.isArray(categories) || categories.length === 0) return '[]';
  return '[\n' + categories.map(cat => {
    const items = Array.isArray(cat.items) ? cat.items : [];
    return `      { name: ${JSON.stringify(cat.name || '')}, items: ${JSON.stringify(items)} }`;
  }).join(', ') + ',\n    ]';
}

// ── 从 userData 读取字段（兼容 server.exe 可能生成的不同结构）──
const zhName = s(userData.name || userData.zhName || userData.nameCn || 'Your Name');
const enName = s(userData.nameEn || userData.englishName || userData.name || 'Your Name');
const title = s(userData.title || userData.titleZh || '金融 + 数据分析');
const titleEn = s(userData.titleEn || userData.title || 'Finance + Data Analytics');
const description = s(userData.description || userData.intro || userData.summary || '');
const descriptionEn = s(userData.descriptionEn || userData.description || '');
const email = s(userData.email || '');
const phone = s(userData.phone || '');
const github = s(userData.github || '');
const linkedin = s(userData.linkedin || '');

// 教育信息
const edu = userData.education || userData.edu || {};
const school = s(edu.school || userData.school || '');
const schoolEn = s(edu.schoolEn || edu.school || userData.school || '');
const degree = s(edu.degree || userData.degree || '');
const degreeEn = s(edu.degreeEn || edu.degree || '');
const period = s(edu.period || userData.eduPeriod || '');
const gpa = s(edu.gpa || userData.gpa || '');
const honors = s(edu.honors || userData.honors || '');

// 经历、项目、技能
const expItems = userData.experience || userData.experiences || userData.internships || [];
const projItems = userData.projects || userData.project || [];
const skillCats = userData.skills || userData.skillCategories || [];
const skillCatsEn = userData.skillsEn || skillCats.map(c => ({
  ...c,
  name: c.nameEn || c.name
}));

const pageContent = `// Auto-generated by deploy script
'use client'
import { useState } from 'react'
const content = {
  zh: {
    nav: { about: '关于我', experience: '实习经历', projects: '项目经历', skills: '技能证书', contact: '联系方式' },
    hero: { name: ${JSON.stringify(zhName)}, title: ${JSON.stringify(title)}, description: ${JSON.stringify(description || s(userData.intro, ''))}, email: ${JSON.stringify(email)} },
    about: { title: '关于我', intro: ${JSON.stringify(description || s(userData.intro, ''))}, education: { school: ${JSON.stringify(school)}, degree: ${JSON.stringify(degree)}, period: ${JSON.stringify(period)}, gpa: ${JSON.stringify(gpa)}, honors: ${JSON.stringify(honors)} } },
    experience: { title: '实习经历', items: ${buildExperienceItems(expItems)} },
    projects: { title: '项目经历', items: ${buildProjectItems(projItems)} },
    skills: { title: '技能 & 证书', categories: ${buildSkillCategories(skillCats)} },
    contact: { title: '联系方式', email: ${JSON.stringify(email)}, phone: ${JSON.stringify(phone)}, github: ${JSON.stringify(github)}, linkedin: ${JSON.stringify(linkedin)} },
  },
  en: {
    nav: { about: 'About', experience: 'Experience', projects: 'Projects', skills: 'Skills', contact: 'Contact' },
    hero: { name: ${JSON.stringify(enName)}, title: ${JSON.stringify(titleEn)}, description: ${JSON.stringify(descriptionEn || description || '')}, email: ${JSON.stringify(email)} },
    about: { title: 'About Me', intro: ${JSON.stringify(descriptionEn || description || '')}, education: { school: ${JSON.stringify(schoolEn)}, degree: ${JSON.stringify(degreeEn || degree)}, period: ${JSON.stringify(period)}, gpa: ${JSON.stringify(gpa)}, honors: ${JSON.stringify(honors)} } },
    experience: { title: 'Experience', items: ${buildExperienceItems(expItems.map(exp => ({
  ...exp,
  company: exp.companyEn || exp.company,
  role: exp.roleEn || exp.role,
  period: exp.periodEn || exp.period,
  highlights: exp.highlightsEn || exp.highlights || [],
  highlightsEn: exp.highlightsEn || exp.highlights || [],
})))} },
    projects: { title: 'Projects', items: ${buildProjectItems(projItems.map(p => ({
  ...p,
  title: p.titleEn || p.title,
  subtitle: p.subtitleEn || p.subtitle,
  objective: p.objectiveEn || p.objective || p.description || '',
  objectiveEn: p.objectiveEn || p.objective || p.description || '',
})))} },
    skills: { title: 'Skills & Certifications', categories: ${buildSkillCategories(skillCatsEn)} },
    contact: { title: 'Contact', email: ${JSON.stringify(email)}, phone: ${JSON.stringify(phone)}, github: ${JSON.stringify(github)}, linkedin: ${JSON.stringify(linkedin)} },
  },
}
type Lang = 'zh' | 'en'
type Content = typeof content.zh
export default function HomePage() {
  const [lang, setLang] = useState<Lang>('zh')
  const t: Content = content[lang]
  return (
    <div className="min-h-screen bg-white">
      <nav className="fixed top-0 w-full bg-white/80 backdrop-blur-sm z-50 border-b border-gray-100">
        <div className="max-w-5xl mx-auto px-6 py-4 flex justify-between items-center">
          <span className="font-bold text-lg text-primary-700">{t.hero.name}</span>
          <div className="flex items-center gap-6">
            <a href="#about" className="text-sm text-gray-600 hover:text-primary-600">{t.nav.about}</a>
            <a href="#experience" className="text-sm text-gray-600 hover:text-primary-600">{t.nav.experience}</a>
            <a href="#projects" className="text-sm text-gray-600 hover:text-primary-600">{t.nav.projects}</a>
            <a href="#skills" className="text-sm text-gray-600 hover:text-primary-600">{t.nav.skills}</a>
            <a href="#contact" className="text-sm text-gray-600 hover:text-primary-600">{t.nav.contact}</a>
            <button onClick={() => setLang(lang === 'zh' ? 'en' : 'zh')} className="text-sm px-3 py-1 rounded-full bg-gray-100 hover:bg-gray-200">{lang === 'zh' ? 'EN' : '中文'}</button>
          </div>
        </div>
      </nav>
      <section className="pt-32 pb-20 px-6"><div className="max-w-5xl mx-auto">
        <h1 className="text-5xl font-bold text-gray-900 mb-4">{t.hero.name}</h1>
        <p className="text-xl text-primary-600 mb-6">{t.hero.title}</p>
        <p className="text-gray-600 max-w-2xl">{t.hero.description}</p>
      </div></section>
      <section id="about" className="py-20 px-6 bg-gray-50"><div className="max-w-5xl mx-auto">
        <h2 className="text-3xl font-bold text-gray-900 mb-8">{t.about.title}</h2>
        <p className="text-gray-600 mb-8">{t.about.intro}</p>
        <div className="bg-white rounded-xl p-6 shadow-sm"><h3 className="font-semibold text-lg mb-4">🎓 {t.about.education.school}</h3>
          <p className="text-gray-600">{t.about.education.degree} · {t.about.education.period}</p>
          {t.about.education.gpa && <p className="text-gray-500 mt-2">GPA: {t.about.education.gpa}</p>}
          {t.about.education.honors && <p className="text-gray-500">{t.about.education.honors}</p>}
        </div>
      </div></section>
      <section id="experience" className="py-20 px-6"><div className="max-w-5xl mx-auto">
        <h2 className="text-3xl font-bold text-gray-900 mb-8">{t.experience.title}</h2>
        <div className="space-y-6">{t.experience.items.map((exp: any, i: number) => (
          <div key={i} className="bg-white border border-gray-200 rounded-xl p-6">
            <div className="flex justify-between items-start mb-4"><div><h3 className="font-semibold text-lg">{exp.company}</h3><p className="text-primary-600">{exp.role}</p></div><span className="text-sm text-gray-500">{exp.period}</span></div>
            <ul className="space-y-2">{exp.highlights.map((h: string, j: number) => (<li key={j} className="text-gray-600 flex items-start gap-2"><span className="text-primary-500 mt-1">•</span>{h}</li>))}</ul>
          </div>))}</div>
      </div></section>
      <section id="projects" className="py-20 px-6 bg-gray-50"><div className="max-w-5xl mx-auto">
        <h2 className="text-3xl font-bold text-gray-900 mb-8">{t.projects.title}</h2>
        <div className="grid md:grid-cols-2 gap-6">{t.projects.items.map((proj: any, i: number) => (
          <div key={i} className="bg-white rounded-xl p-6 shadow-sm"><h3 className="font-semibold text-lg mb-2">{proj.title}</h3>
            {proj.tech?.length > 0 && <div className="flex flex-wrap gap-2 mb-3">{proj.tech.map((tech: string, j: number) => (<span key={j} className="text-xs px-2 py-1 bg-primary-50 text-primary-700 rounded-full">{tech}</span>))}</div>}
            <p className="text-gray-600 text-sm">{proj.objective}</p>
          </div>))}</div>
      </div></section>
      <section id="skills" className="py-20 px-6"><div className="max-w-5xl mx-auto">
        <h2 className="text-3xl font-bold text-gray-900 mb-8">{t.skills.title}</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{t.skills.categories.filter((c: any) => c.items.length > 0).map((cat: any, i: number) => (
          <div key={i} className="bg-white border border-gray-200 rounded-xl p-6"><h3 className="font-semibold mb-4">{cat.name}</h3>
            <div className="flex flex-wrap gap-2">{cat.items.map((item: string, j: number) => (<span key={j} className="text-sm px-3 py-1 bg-gray-100 rounded-full">{item}</span>))}</div>
          </div>))}</div>
      </div></section>
      <section id="contact" className="py-20 px-6 bg-gray-900 text-white"><div className="max-w-5xl mx-auto text-center">
        <h2 className="text-3xl font-bold mb-8">{t.contact.title}</h2>
        <div className="flex flex-wrap justify-center gap-6">
          {t.contact.email && <a href={\`mailto:\${t.contact.email}\`} className="text-gray-300 hover:text-white">📧 {t.contact.email}</a>}
          {t.contact.github && <a href={t.contact.github} target="_blank" className="text-gray-300 hover:text-white">💻 GitHub</a>}
          {t.contact.linkedin && <a href={t.contact.linkedin} target="_blank" className="text-gray-300 hover:text-white">🔗 LinkedIn</a>}
          {t.contact.phone && <span className="text-gray-300">📱 {t.contact.phone}</span>}
        </div>
      </div></section>
      <footer className="py-6 text-center text-gray-400 text-sm">Built with Personal Report · Next.js</footer>
    </div>
  )
}
`;

try {
  fs.writeFileSync(outputPath, pageContent, 'utf-8');
  console.log('✓ page.tsx 已生成：' + outputPath);
} catch (e) {
  console.error('写入 page.tsx 失败：' + e.message);
  process.exit(1);
}
